name: Build Resource Pack

on:
  push:
  pull_request:

jobs:
  build-resourcepack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Build resourcepack
        run: npm run buildResourcePack

      - name: Upload resourcepack artifact
        uses: actions/upload-artifact@v7
        with:
          name: resourcepack
          path: dist/*.zip
          if-no-files-found: error
