name: Build Datapack

on:
  push:
  pull_request:

jobs:
  build-datapack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Build datapack
        run: npm run build

      - name: Upload datapack artifact
        uses: actions/upload-artifact@v4
        with:
          name: datapack
          path: dist/*.zip
          if-no-files-found: error
